[package]
name = "kagami"
version = "0.0.1"
authors = ["Oery"]
edition = "2024"
description = "A Minecraft network based modding interface"
repository = "https://github.com/oery/kagami"
keywords = ["minecraft", "modding", "network", "proxy"]
categories = ["game-development", "network-programming"]
license = "MIT"

[dependencies]
futures = "0.3.31"
async-std = { version = "1.13.1", features = ["attributes"] }
serde = "1.0.219"
nom = "8.0.0"
thiserror = "2.0.12"
tracing = "0.1.41"
atomic_enum = "0.3.0"
strum = { version = "0.27.2", features = ["derive"] }
flate2 = "1.1.2"

